### ISSUE TITLE
TODO: implement RDF/RDFS entailment semantics as described here

### ISSUE THREAD

**Issue by RichDijk** [gtfierro/reasonable#18]
This TODO is in the readme. Is it still the case that RDF/RDFS entailments are not yet implemented?

**Comment by gtfierro** [comment]
Hi @RichDijk -- I believe many of these are implemented but were accidentally grouped under the OWL-RL rules. Most of 9.2.1 in https://www.w3.org/TR/rdf11-mt/#entailment-rules-informative should already be implemented save for some of the basic ones like asserting `rdfs:Resource`, `ref:Property`, etc

**Comment by RichDijk** [comment]
Good, I expected something like that. Thank you.
