### ISSUE TITLE
Minimal example breaks with `IndentationError`

### ISSUE THREAD

**Issue by lu-pl** [gtfierro/reasonable#21]
Environment:
- Arch Linux
- Python 3.11
- reasonable 0.2.1

Minimal example: 
```python
from rdflib import Graph, Namespace
from rdflib.namespace import OWL

import reasonable

ex = Namespace("http://example.org/")

graph = Graph()
graph.add((ex.subj, ex.pred, ex.obj))
graph.add((ex.inverse, OWL.inverseOf, ex.pred))

r = reasonable.PyReasoner()
r.from_graph(graph)
```

`r.from_graph(graph)` breaks with 

```
    [...]
    # r.from_graph(graph)
    ^^^^^^^^^^^^^^^^^^^
  File "converters.pg", line 2
    def get_triples(graph):
IndentationError: unexpected indent
```

**Comment by lu-pl** [comment]
Sorry for the late reply, just tried it with `reasonable==0.2.2a3`: same problem, `IndentationError`.

**Comment by gtfierro** [comment]
I'm sorry, I meant `reasonable==0.2.2a4` -- this seems to work ok for me when I try locally.

**Comment by lu-pl** [comment]
Thanks, `reasonable==0.2.2a4` works fine!

What is the course of action now, should I just use `reasonable==0.2.2a4` in production or will there be a new release?

**Comment by gtfierro** [comment]
`reasonable==0.2.2` release was just published so you don't have to worry about the pre-release. Closing for now -- let me know if you run into any issues
