### ISSUE TITLE
Standalone application available? Binary shows errors

### ISSUE THREAD

**Issue by k00ni** [gtfierro/reasonable#24]
I would like to try the reasoner out, so I picked the binary you are providing in the latest release [nightly build 023-06-13](https://github.com/gtfierro/reasonable/releases/tag/nightly): https://github.com/gtfierro/reasonable/releases/download/nightly/reasonable

When running it in Ubuntu 20.04. I get the following errors:

> ./reasonable            

> ./reasonable: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./reasonable)

> ./reasonable: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./reasonable)

> ./reasonable: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./reasonable)

Is that file even meant to be used in that way? In the documentation at https://docs.rs/reasonable/latest/reasonable/ it says there is also a binary available. If so, I'd appreciate if you could give me a short overview, because I have no knowledge in Rust or Python. Thank you.

**Comment by gtfierro** [comment]
You are using it the right way, but it looks like you'll need a newer version of libc installed for this to run.

As an alternative, I've created a static build of `reasonable` that will be available in the next nightly release that should solve the libc dependency issue you are seeing. You can give it a try [here](https://home.gtf.fyi/files/reasonable-static)

**Comment by k00ni** [comment]
Still the same:

```
./reasonable-static: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./reasonable-static)
./reasonable-static: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./reasonable-static)
./reasonable-static: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./reasonable-static)
```

Should I install something to solve it?

**Comment by gtfierro** [comment]
Make sure you have libc installed (I think it's the `libc6-dev` package?). I'm traveling this week but I'll see if I can reproduce the issue you are seeing

**Comment by k00ni** [comment]
Turns out, I already have it installed (**2.31-0ubuntu9.9**):

```
sudo apt-get install libc6-dev
[sudo] Passwort für ka: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
libc6-dev ist schon die neueste Version (2.31-0ubuntu9.9).
```
I am running latest Ubuntu 20.04.

> I'm traveling this week but I'll see if I can reproduce the issue you are seeing

Thank you for your time. Looking forward

**Comment by gtfierro** [comment]
Hi @k00ni ! Sorry for the delay. Can you try [this](https://github.com/gtfierro/reasonable/releases/download/nightly/reasonable-static)? I just ran it on a fresh 20.04 container and it seemed to work fine

**Comment by k00ni** [comment]
https://github.com/gtfierro/reasonable/releases/download/nightly/reasonable-static leads to a `Page not found` page.

**Comment by gtfierro** [comment]
Sorry! I forgot to update one of the other build scripts. https://github.com/gtfierro/reasonable/releases/download/nightly/reasonable-static should work now

**Comment by k00ni** [comment]
Thank you for your fast reply. There are no errors anymore, but when running the file in Terminal there is no output. Maybe I am using it the wrong way?

```
➜ chmod +x reasonable-static 
➜ ./reasonable-static
```

**Comment by gtfierro** [comment]
Usage is pretty straightforward from reading the `src/main.rs` file but I added a barebones CLI on top; download is available at the same link (https://github.com/gtfierro/reasonable/releases/download/nightly/reasonable-static)

**Comment by k00ni** [comment]
Thank you, that is helpful! All good now.
