### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by rue-a** [gtfierro/reasonable#4]
Hi,
The package seems to be pretty neat. Sadly I can't get it installed on my system. At first I tried via pip which led to a successful installation, but the folder containing the package was empty.

pip install:
![image](https://user-images.githubusercontent.com/25478579/89422765-088ebf00-d736-11ea-860f-21ce841f615f.png)

installed package:
![image](https://user-images.githubusercontent.com/25478579/89423274-92d72300-d736-11ea-9c8f-370be7ec05dd.png)

I then downloaded the repo from github. I installed Rust via rustup (never had contact with Rust). Fianlly I tried make, as well as cargo build --release from cmd, which both led to the same error (that is cryptic to me):

![image](https://user-images.githubusercontent.com/25478579/89423906-6243b900-d737-11ea-9f24-9fa27f155776.png)

**Comment by gtfierro** [comment]
Thanks for trying out the package, @rue-a ! Unfortunately, the package only supports Python3 + Linux right now because I haven't had the time to figure out how to set up the build/linking configuration for the [pyo3 stuff](https://pyo3.rs/v0.11.1/building_and_distribution.html). I'll try to find some time to work on that coming soon

**Comment by rue-a** [comment]
> Thanks for trying out the package, @rue-a ! Unfortunately, the package only supports Python3 + Linux right now because I haven't had the time to figure out how to set up the build/linking configuration for the [pyo3 stuff](https://pyo3.rs/v0.11.1/building_and_distribution.html). I'll try to find some time to work on that coming soon

**Comment by rue-a** [comment]
Ah! That explains it, I'm looking forward to it. Thank you.
